name: Test artifacts upload and download

on:
  push:
    paths:
      - '**/artifacts.yaml'
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p characters
          echo "Harry Potter" > characters/harry.txt
          echo "Hermione Granger" > characters/hermione.txt
          echo "Albus Dumbledore" > characters/albus.txt
          echo "J.K. Rowling" > author.txt

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          # You can specify multiple paths, and exclusions using '!'
          path: |
            ./author.txt
            ./characters/
            !./characters/albus*

  download:
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: Display structure of downloaded files
        run: ls -R
