name: Reusable workflow

on:
  workflow_call:
    inputs:
      name:
        description: "The user name"
        type: string
        required: true
      age:
        description: "The user age"
        type: number
        required: true
    secrets:
      token:
        required: true
    # Map the workflow outputs to job outputs
    outputs:
      output1:
        description: "The first output string"
        value: ${{ jobs.example_job.outputs.output1 }}
      output2:
        description: "The second output string"
        value: ${{ jobs.example_job.outputs.output2 }}

jobs:
  example_job:
    name: Generate output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      output1: ${{ steps.step1.outputs.output1}}
      output2: ${{ steps.step2.outputs.output2 }}
    steps:
      - id: step1
        # set step output
        run: echo "output1=${{ inputs.name }} is ${{ inputs.age }}" >> $GITHUB_OUTPUT
      - id: step2
        run: |
          token=${{ secrets.token }}
          echo "output2='token length ${#token}'" >> $GITHUB_OUTPUT
