name: Call a reusable workflow

on:
  workflow_dispatch:

jobs:
  job1:
    name: Calling a reusable workflow
    uses: ./.github/workflows/called.yaml
    with:
      name: Gary
      age: 30
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  job2:
    name: Use output of a reusable workflow
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.output1 }} ${{ needs.job1.outputs.output2 }}
