name: Matrix dynamic

on:
  push:
    branches:
      - matrix_dynamic
  workflow_dispatch:
    inputs:
      zone:
        type: choice
        description: Environment to target
        default: Australia
        options:
          - Australia
          - USA

env:
  zone: ${{ inputs.zone || 'Australia' }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.set-matrix.outputs.targets }}
      zone: ${{ env.zone }}
    steps:
      - uses: actions/checkout@v1
      - id: set-matrix
        run: echo "targets=$(jq -c . < demo.json)" >> $GITHUB_OUTPUT

  print:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.prepare.outputs.targets }}
      - run: echo ${{ fromJson(needs.prepare.outputs.targets) }}
      - run: echo ${{ (fromJson(needs.prepare.outputs.targets))[needs.prepare.outputs.zone] }}


  # plan:
  #   needs: prepare
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       targets: ${{ (fromJson(needs.prepare.outputs.targets))[needs.prepare.outputs.zone] }}
  #   steps:
  #     - run: echo "plan"

  # apply:
  #   needs: ['prepare', 'plan']
  #   runs-on: ubuntu-latest
  #   strategy:
  #     max-parallel: 1
  #     matrix:
  #       targets: ${{ (fromJson(needs.prepare.outputs.targets))[needs.prepare.outputs.zone] }}
  #   steps:
  #     - run: echo "apply"
