name: Test strategy.matrix

on:
  workflow_dispatch:

jobs:
  job1:
    strategy:
      matrix:
        target: [dev, stage, prod]
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello ${{ matrix.target }}
