name: Test strategy.matrix

on:
  push:
    branches:
      - matrix
  workflow_dispatch:

jobs:
  job1:
    strategy:
      matrix:
        target: [dev, stage, prod]
    runs-on: ubuntu-latest
    steps:
      - run: echo "var_${{matrix.target}}=${{matrix.target}}" >> "$GITHUB_OUTPUT"
        id: step1


  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Use output of previous step
        env:
          matrix_output: ${{ toJson(needs.job1.outputs) }}
        run: echo "Output from matrix step is $matrix_output"
