name: Test strategy.matrix

on:
  push:
    branches:
      - matrix
  workflow_dispatch:

jobs:
  job1:
    strategy:
      max-parallel: 1
      matrix:
        target: [dev, stage, prod]
    runs-on: ubuntu-latest
    steps:
      - run: echo $target
        env:
          target: ${{ matrix.target }}
        id: step1
