name: Matrix dynamic

on:
  push:
    branches:
      - matrix_dynamic
  workflow_dispatch:
    inputs:
      zone:
        type: choice
        description: Environment to target
        default: Australia
        options:
          - Australia
          - USA

env:
  zone: ${{ inputs.zone || 'Australia' }}
  Australia: '["dev", "prod"]'
  USA:       '["prod"]'

jobs:
  plan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ${{ env[env.zone] }}
    steps:
      - run: |
          echo "hello"
