# There is no easy way to set dynamic keys in matrix output
# So we ust artifacts as a workaround, see: https://github.com/orgs/community/discussions/17245
name: Test matrix_output

on:
  push:
    paths:
      - '**/matrix_output.yaml'
  workflow_dispatch:

env:
  stages: '[]'

jobs:
  job1:

    strategy:
      matrix:
        target: ${{ fromJson(env.stages) }}
    runs-on: ubuntu-latest
    outputs:
      # !! can't set dynamic keys, you need to use artifacts as a workaround to pass data to next job
      dev: ${{ steps.step1.outputs.var_dev }}
      stage: ${{ steps.step1.outputs.var_stage}}
      prod: ${{ steps.step1.outputs.var_prod }}
    steps:
      - run: echo "var_${{matrix.target}}=${{matrix.target}}" >> "$GITHUB_OUTPUT"
        id: step1

  job2:
    runs-on: ubuntu-latest
    needs: job1
    env:
      matrix_job: ${{ toJson(needs.job1) }}
    steps:
      - run: echo "Print needs.job1 $matrix_job"
