name: Matrix dynamic

on:
  push:
    branches:
      - matrix_dynamic
  workflow_dispatch:
    inputs:
      zone:
        type: choice
        description: Environment to target
        default: Australia
        options:
          - Australia
          - USA

env:
  zone: ${{ inputs.zone || 'Australia' }}
  targets:
  Australia: '[\"dev\",\"prod\"]'
  USA:       '[\"prod\"]'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.set-matrix.outputs.targets }}
    steps:
      - id: set-matrix
        run: echo "targets='${{ env[env.zone] }}'" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - run: echo ${{ needs.prepare.outputs.targets }}
      - run: echo ${{ fromJSON(needs.prepare.outputs.targets) }}

  plan:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets: ${{ needs.prepare.outputs.targets }}
    steps:
      - run: echo "plan"

  apply:
    needs: plan
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        targets: ${{ fromJSON(needs.prepare.outputs.targets) }}
    steps:
      - run: echo "apply"
