name: Matrix empty

on:
  push:
    paths:
      - '**/matrix_empty.yaml'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      targets: '[]'
    steps:
      - id: set-matrix
        run: echo "hello"

  plan:
    needs: prepare
    runs-on: ubuntu-latest
    if: ${{ needs.prepare.outputs.targets != '[]' }} # skip this if no targets
    strategy:
      matrix:
        target: ${{ fromJson(needs.prepare.outputs.targets) }}
    steps:
      - run: echo "plan $target"
        env:
          target: ${{ matrix.target }}
