name: Steps outputs

on:
  push:
    branches:
      - autorun
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: |
          echo "Hello world"
          echo "Another line"
          ls non-existing-file.txt
        continue-on-error: true

      - name: Show outputs of previous step
        run: |
          echo "Step 1 outputs:"
          echo "  ${{ steps.step1.outputs }}"
